FROM node:current-alpine AS builder

WORKDIR /app

COPY package.json . 
COPY package-lock.json .

RUN npm ci --legacy-peer-deps

COPY . /app

RUN npm run build

# Switch to the scratch image
FROM nginx:latest

EXPOSE 80

COPY --from=builder /app/dist /usr/share/nginx/html
